version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mono-squid_web_1
      APP_PORT: 80

  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${APP_DATA_DIR}/data/index.html:/usr/share/nginx/html/index.html:ro
      - /home/umbrel/umbrel/home/Downloads/music/squid:/downloads
    networks:
      default:
        ipv4_address: $APP_MONO_SQUID_WEB_IP




