version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mono-squid_browser_1
      APP_PORT: 3000

  browser:
    image: lscr.io/linuxserver/chromium:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - CHROME_CLI=https://mono.squid.wtf/
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - /home/umbrel/umbrel/home/Downloads/music/squid:/config/Downloads:/config/Downloads
    shm_size: "2gb"
    networks:
      default:
        ipv4_address: $APP_MONO_SQUID_BROWSER_IP
