version: '3.7'

services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: monosquid_web
      APP_PORT: 3000
    networks:
      - default

  monosquid_web:
    image: ghcr.io/thesquid777/monosquid:latest
    container_name: monosquid_web
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
      - /home/umbrel/umbrel/home/Downloads/music/squid:/config/Downloads
    networks:
      - default

networks:
  default:
    name: monosquid_network
