version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pkvault_web_1
      APP_PORT: 3000
    depends_on:
      - web

  web:
    image: ghcr.io/chnapy/pkvault:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/pkvault
      - ${APP_DATA_DIR}/saves:/pkvault/saves
