version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: anticristiancpu-soulsync_web_1
      APP_PORT: 8008

  web:
    image: boulderbadgedad/soulsync:latest
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    ports:
      - "8888:8888"
      - "8889:8889"
      - "8008:8008"
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
      - soulsync_database:/app/data
      - ${APP_DATA_DIR}/data/logs:/app/logs
      - /home/umbrel/umbrel/home/Downloads/complete:/app/downloads
      - /home/umbrel/umbrel/home/Downloads/music/SoulSync:/app/Transfer

volumes:
  soulsync_database:
