version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: anticristiancpu-openwakeword_server_1
      APP_PORT: 10400
      PROXY_AUTH_ADD: "false"

  server:
    image: rhasspy/wyoming-openwakeword:2.1.0
    restart: on-failure
    environment:
      TZ: "Europe/Rome"
    command:
      - "--custom-model-dir"
      - "/custom"
      - "--threshold"
      - "0.5"
      - "--trigger-level"
      - "1"
    ports:
      - "10400:10400"
    volumes:
      - ${APP_DATA_DIR}/custom:/custom
