version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: anticristiancpu-pinakes_web_1
      APP_PORT: 8081

  web:
    image: jbenamy/pinakes:latest
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /home/umbrel/umbrel/external/CRISTIAN-HDD:/media/books
