version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: anticristiancpu-piper_server_1
      APP_PORT: 5000

  server:
    image: rhasspy/wyoming-piper:2.4.2
    restart: on-failure
    environment:
      TZ: "Europe/Rome"
    command:
      - "--voice"
      - "it_IT-paola-medium"
      - "--web-server"
      - "--web-server-host"
      - "0.0.0.0"
    ports:
      - "10200:10200"
    volumes:
      - ${APP_DATA_DIR}/data:/data
