version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: anticristiancpu-grimmory_web_1
      APP_PORT: 6060

  web:
    image: ghcr.io/grimmory-tools/grimmory:latest
    restart: on-failure
    environment:
      APP_USER_ID: "1000"
      APP_GROUP_ID: "1000"
      TZ: "Europe/Rome"
      DATABASE_URL: "jdbc:mariadb://mariadb:3306/grimmory"
      DB_USER: "grimmory"
      DB_PASSWORD: "grimmory_pass"
      DISK_TYPE: "LOCAL"
    depends_on:
      - mariadb
    volumes:
      - ${APP_DATA_DIR}/data/app:/app/data
      - ${APP_DATA_DIR}/data/books:/books
      - ${APP_DATA_DIR}/data/bookdrop:/bookdrop

  mariadb:
    image: mariadb:10.11
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "grimmory_root"
      MYSQL_DATABASE: "grimmory"
      MYSQL_USER: "grimmory"
      MYSQL_PASSWORD: "grimmory_pass"
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
