version: "3.7"

services:
  grimmory:
    image: ghcr.io/grimmory-tools/grimmory:latest
    container_name: grimmory
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "${APP_GRIMMORY_PORT:-6060}:6060"
    environment:
      - APP_USER_ID=1000
      - APP_GROUP_ID=1000
      - TZ=Europe/Rome
      - DATABASE_URL=jdbc:mariadb://mariadb:3306/grimmory
      - DB_USER=grimmory
      - DB_PASSWORD=ChangeMe_Grimmory_2025!
      - DISK_TYPE=LOCAL
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
      - "${APP_DATA_DIR}/books:/books"
      - "${APP_DATA_DIR}/bookdrop:/bookdrop"
    networks:
      - grimmory_network

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: grimmory-mariadb
    restart: unless-stopped
    environment:
      - DB_USER_ID=1000
      - DB_GROUP_ID=1000
      - MYSQL_ROOT_PASSWORD=ChangeMe_Root_2025!
      - MYSQL_DATABASE=grimmory
      - MYSQL_USER=grimmory
      - MYSQL_PASSWORD=ChangeMe_Grimmory_2025!
    volumes:
      - "${APP_DATA_DIR}/mariadb:/config"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - grimmory_network

networks:
  grimmory_network:
    driver: bridge
