name: Auto-Update Libation

on:
  schedule:
    - cron: '30 3 * * *' 
  workflow_dispatch: 

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Scarica il repository
        uses: actions/checkout@v4

      - name: Cerca l'ultima release
        run: |
          LATEST_VERSION=$(curl -sL https://api.github.com/repos/rmcrackan/Libation/releases/latest | jq -r ".tag_name")
          echo "Ultima versione: $LATEST_VERSION"
          
          if [ "$LATEST_VERSION" != "null" ] && [ -n "$LATEST_VERSION" ]; then
            sed -i "s/^version: .*/version: \"$LATEST_VERSION\"/" anticristiancpu-libation/umbrel-app.yml
          fi

      - name: Salva e chiudi
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add anticristiancpu-libation/umbrel-app.yml
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update Libation" && git push)
